//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatColonia
    {
        public CatColonia()
        {
            this.DomicilioES = new HashSet<DomicilioES>();
        }
    
        public int ID { get; set; }
        public string NombreColonia { get; set; }
        public Nullable<long> CP { get; set; }
        public int IdMunicipio { get; set; }
    
        public virtual CatMunicipio CatMunicipio { get; set; }
        public virtual ICollection<DomicilioES> DomicilioES { get; set; }
    }
}
