//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMunicipio
    {
        public CatMunicipio()
        {
            this.CatColonia = new HashSet<CatColonia>();
        }
    
        public int ID { get; set; }
        public string NombreMunicipio { get; set; }
        public int IdEstado { get; set; }
    
        public virtual ICollection<CatColonia> CatColonia { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
