//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPais
    {
        public CatPais()
        {
            this.CatEstado = new HashSet<CatEstado>();
        }
    
        public int ID { get; set; }
        public string NombrePais { get; set; }
    
        public virtual ICollection<CatEstado> CatEstado { get; set; }
    }
}
