//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatRoles
    {
        public CatRoles()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int ID { get; set; }
        public string NombreRol { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
