//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultorios
    {
        public Consultorios()
        {
            this.Citas = new HashSet<Citas>();
            this.ConsultoriosTipos = new HashSet<ConsultoriosTipos>();
            this.DisponibilidadConsultorios = new HashSet<DisponibilidadConsultorios>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public bool Planta { get; set; }
        public bool Activo { get; set; }
        public int IdUsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ICollection<ConsultoriosTipos> ConsultoriosTipos { get; set; }
        public virtual ICollection<DisponibilidadConsultorios> DisponibilidadConsultorios { get; set; }
    }
}
