//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosGeneralesES
    {
        public DatosGeneralesES()
        {
            this.EstudioSocioeconomico = new HashSet<EstudioSocioeconomico>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public Nullable<int> IdDomicilio { get; set; }
        public string EstadoCivil { get; set; }
        public string TelefonoFijo { get; set; }
        public string Celular { get; set; }
    
        public virtual DomicilioES DomicilioES { get; set; }
        public virtual ICollection<EstudioSocioeconomico> EstudioSocioeconomico { get; set; }
    }
}
