//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosViviendaES
    {
        public DatosViviendaES()
        {
            this.EstudioSocioeconomico = new HashSet<EstudioSocioeconomico>();
        }
    
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Antiguedad { get; set; }
        public string ViasAcceso { get; set; }
        public string CentrosComerciales { get; set; }
        public string ServiciosPublicos { get; set; }
        public Nullable<int> CantidadPersonas { get; set; }
        public Nullable<int> Habitaciones { get; set; }
        public string Condiciones { get; set; }
        public string Distribucion { get; set; }
        public string ProblemasEspacios { get; set; }
    
        public virtual ICollection<EstudioSocioeconomico> EstudioSocioeconomico { get; set; }
    }
}
