//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependientesEconomicosES
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Parentezco { get; set; }
        public string Edad { get; set; }
        public string Ocupacion { get; set; }
        public string ServicioSalud { get; set; }
        public Nullable<int> IdEstudioSocioeconomico { get; set; }
    
        public virtual EstudioSocioeconomico EstudioSocioeconomico { get; set; }
    }
}
