//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dias
    {
        public Dias()
        {
            this.Fechas = new HashSet<Fechas>();
            this.HorarioPsicoterapeuta = new HashSet<HorarioPsicoterapeuta>();
        }
    
        public int ID { get; set; }
        public string NombreDia { get; set; }
    
        public virtual ICollection<Fechas> Fechas { get; set; }
        public virtual ICollection<HorarioPsicoterapeuta> HorarioPsicoterapeuta { get; set; }
    }
}
