//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisponibilidadPsicoterapeuta
    {
        public int ID { get; set; }
        public int IdFecha { get; set; }
        public int IdHora { get; set; }
        public int IdTerapeuta { get; set; }
    
        public virtual Fechas Fechas { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Psicoterapeuta Psicoterapeuta { get; set; }
    }
}
