//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilioES
    {
        public DomicilioES()
        {
            this.DatosGeneralesES = new HashSet<DatosGeneralesES>();
        }
    
        public int ID { get; set; }
        public int IdColonia { get; set; }
        public string Calle { get; set; }
        public Nullable<int> NumExterior { get; set; }
        public Nullable<int> NumInterior { get; set; }
        public string EntreCalle { get; set; }
        public string Ycalle { get; set; }
    
        public virtual CatColonia CatColonia { get; set; }
        public virtual ICollection<DatosGeneralesES> DatosGeneralesES { get; set; }
    }
}
