//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudioSocioeconomico
    {
        public EstudioSocioeconomico()
        {
            this.DependientesEconomicosES = new HashSet<DependientesEconomicosES>();
            this.InformacionBienesES = new HashSet<InformacionBienesES>();
            this.TrabajoActualES = new HashSet<TrabajoActualES>();
        }
    
        public int ID { get; set; }
        public int IdUsuarioEncuestador { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdDatosGenerales { get; set; }
        public decimal IngresosTotales { get; set; }
        public decimal EgresosTotales { get; set; }
        public int NumDependientes { get; set; }
        public Nullable<int> IdDatosVivienda { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public string Observaciones { get; set; }
    
        public virtual DatosGeneralesES DatosGeneralesES { get; set; }
        public virtual DatosViviendaES DatosViviendaES { get; set; }
        public virtual ICollection<DependientesEconomicosES> DependientesEconomicosES { get; set; }
        public virtual ICollection<InformacionBienesES> InformacionBienesES { get; set; }
        public virtual ICollection<TrabajoActualES> TrabajoActualES { get; set; }
    }
}
