//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fechas
    {
        public Fechas()
        {
            this.DisponibilidadConsultorios = new HashSet<DisponibilidadConsultorios>();
            this.DisponibilidadPsicoterapeuta = new HashSet<DisponibilidadPsicoterapeuta>();
        }
    
        public int ID { get; set; }
        public int IdDia { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Dias Dias { get; set; }
        public virtual ICollection<DisponibilidadConsultorios> DisponibilidadConsultorios { get; set; }
        public virtual ICollection<DisponibilidadPsicoterapeuta> DisponibilidadPsicoterapeuta { get; set; }
    }
}
