//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionBienesES
    {
        public int ID { get; set; }
        public string Automovil { get; set; }
        public string Propiedades { get; set; }
        public string Inversiones { get; set; }
        public string Deudas { get; set; }
        public string Otros { get; set; }
        public Nullable<int> IdEstudioSocio { get; set; }
    
        public virtual EstudioSocioeconomico EstudioSocioeconomico { get; set; }
    }
}
