//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Origen { get; set; }
        public string IP { get; set; }
        public string Descripcion { get; set; }
        public byte IdTipoAccion { get; set; }
    
        public virtual TipoAccion TipoAccion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
