//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoTerapeutas
    {
        public int ID { get; set; }
        public int IdCita { get; set; }
        public int IdTerapeuta { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<bool> Pagada { get; set; }
        public Nullable<decimal> SaldoPendiente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Psicoterapeuta Psicoterapeuta { get; set; }
    }
}
