//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsicoterapeutasTiposTrastornos
    {
        public int ID { get; set; }
        public int IdPsicoterapeuta { get; set; }
        public short IdTipoTrastorno { get; set; }
        public bool Activo { get; set; }
    
        public virtual Psicoterapeuta Psicoterapeuta { get; set; }
        public virtual TipoTrastorno TipoTrastorno { get; set; }
    }
}
