//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psicoterapeuta
    {
        public Psicoterapeuta()
        {
            this.Citas = new HashSet<Citas>();
            this.CostosConsultasFijas = new HashSet<CostosConsultasFijas>();
            this.DisponibilidadPsicoterapeuta = new HashSet<DisponibilidadPsicoterapeuta>();
            this.HorarioPsicoterapeuta = new HashSet<HorarioPsicoterapeuta>();
            this.PagoTerapeutas = new HashSet<PagoTerapeutas>();
            this.PsicoterapeutasTiposAreas = new HashSet<PsicoterapeutasTiposAreas>();
            this.PsicoterapeutasTiposPacientes = new HashSet<PsicoterapeutasTiposPacientes>();
            this.PsicoterapeutasTiposTrastornos = new HashSet<PsicoterapeutasTiposTrastornos>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public Nullable<short> IdTurno { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Whatsapp { get; set; }
        public Nullable<short> IdTipoCuota { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ICollection<CostosConsultasFijas> CostosConsultasFijas { get; set; }
        public virtual ICollection<DisponibilidadPsicoterapeuta> DisponibilidadPsicoterapeuta { get; set; }
        public virtual ICollection<HorarioPsicoterapeuta> HorarioPsicoterapeuta { get; set; }
        public virtual ICollection<PagoTerapeutas> PagoTerapeutas { get; set; }
        public virtual TipoCouta TipoCouta { get; set; }
        public virtual Turnos Turnos { get; set; }
        public virtual ICollection<PsicoterapeutasTiposAreas> PsicoterapeutasTiposAreas { get; set; }
        public virtual ICollection<PsicoterapeutasTiposPacientes> PsicoterapeutasTiposPacientes { get; set; }
        public virtual ICollection<PsicoterapeutasTiposTrastornos> PsicoterapeutasTiposTrastornos { get; set; }
    }
}
