//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psicoterapeuta
    {
        public Psicoterapeuta()
        {
            this.Citas = new HashSet<Citas>();
            this.CostosConsultasFijas = new HashSet<CostosConsultasFijas>();
            this.DisponibilidadPsicoterapeuta = new HashSet<DisponibilidadPsicoterapeuta>();
            this.HorarioPsicoterapeuta = new HashSet<HorarioPsicoterapeuta>();
            this.PagoTerapeutas = new HashSet<PagoTerapeutas>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public Nullable<short> IdTurno { get; set; }
        public Nullable<short> IdTipoPaciente { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Whatsapp { get; set; }
        public Nullable<short> IdTipoTrastorno { get; set; }
        public Nullable<short> IdAreaAtiende { get; set; }
        public Nullable<short> IdTipoCuota { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ICollection<CostosConsultasFijas> CostosConsultasFijas { get; set; }
        public virtual ICollection<DisponibilidadPsicoterapeuta> DisponibilidadPsicoterapeuta { get; set; }
        public virtual ICollection<HorarioPsicoterapeuta> HorarioPsicoterapeuta { get; set; }
        public virtual ICollection<PagoTerapeutas> PagoTerapeutas { get; set; }
        public virtual TipoAreas TipoAreas { get; set; }
        public virtual TipoCouta TipoCouta { get; set; }
        public virtual TipoPaciente TipoPaciente { get; set; }
        public virtual TipoTrastorno TipoTrastorno { get; set; }
        public virtual Turnos Turnos { get; set; }
    }
}
