//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosNivelSocioEconomico
    {
        public int ID { get; set; }
        public string NombreTarifa { get; set; }
        public Nullable<decimal> RangoInferior { get; set; }
        public Nullable<decimal> RangoSuperior { get; set; }
        public decimal PrecioTarifa { get; set; }
        public string DescuentoPorPerExtra { get; set; }
    }
}
