//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPago
    {
        public TipoPago()
        {
            this.CobroConsulta = new HashSet<CobroConsulta>();
        }
    
        public int ID { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<CobroConsulta> CobroConsulta { get; set; }
    }
}
