//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAccion
    {
        public TipoAccion()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public byte ID { get; set; }
        public string Accion { get; set; }
    
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
