//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoActualES
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string Area { get; set; }
        public string Telefono { get; set; }
        public string Horario { get; set; }
        public int IdEstudioSocioeconomico { get; set; }
    
        public virtual EstudioSocioeconomico EstudioSocioeconomico { get; set; }
    }
}
