//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutores
    {
        public Tutores()
        {
            this.Pacientes = new HashSet<Pacientes>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string ViaContacto { get; set; }
        public string Parentezco { get; set; }
    
        public virtual ICollection<Pacientes> Pacientes { get; set; }
    }
}
