//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Logs = new HashSet<Logs>();
            this.Permisos = new HashSet<Permisos>();
            this.MenuUsuario = new HashSet<MenuUsuario>();
        }
    
        public int ID { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string NombreUsuario { get; set; }
        public byte[] Contraseña { get; set; }
        public bool Activo { get; set; }
        public int RolId { get; set; }
    
        public virtual CatRoles CatRoles { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual ICollection<Permisos> Permisos { get; set; }
        public virtual ICollection<MenuUsuario> MenuUsuario { get; set; }
    }
}
